### ISSUE TITLE
Resource path (basepath) incorrectly determined

### ISSUE THREAD

**Issue by Niellles** [AniSkywalker/SarcasmDetection#5]
I am running into an error that's caused by line 286 of `sarcasm_detection_model_CNN_LSTM_DNN.py`. As you can see the string slice, to get the directory above the working directory, with index ` os.getcwd().rfind('/')` doesn't work with a path that contains backslashes instead of forward slashes (as is the case in Windows).

> Traceback (most recent call last): 
>   File "sarcasm_detection_model_CNN_LSTM_DNN.py", line 303, in <module>
>     t.load_trained_model(weight_file='weights.05__.hdf5')
>   File "sarcasm_detection_model_CNN_LSTM_DNN.py", line 201, in load_trained_model
>     self.__load_model(self._model_file_path + model_file, self._model_file_path + weight_file)
>   File "sarcasm_detection_model_CNN_LSTM_DNN.py", line 206, in __load_model
>     self.model = model_from_json(open(model_path).read())
> FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\Niels\\Documents\\Maaksels\\SarcasmDetection\\sr\resource/text_model/weights/model.json'

## Fix
```
basepath = os.path.abspath(os.path.join(os.getcwd(), '..'))
```
Should work, and achieve the desired result, for both Windows and Unix style paths.

I'll be committing this fix to the [pull request](https://github.com/AniSkywalker/SarcasmDetection/pull/4) that I've already made.

**Comment by Niellles** [comment]
Fixed and merged in #4
